// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "graphqlEndpoint": "https://2aiash74x5dyhbelou6ayuz3qm.appsync-api.us-east-1.amazonaws.com/graphql",
    "region": "us-east-1",
    "authenticationType": "API_KEY",
    "apiKey": "da2-esho6eluvfdgvlbjpye2cgtjpu",
};

export default awsmobile;